### ISSUE TITLE
Allow widget as icon item

### ISSUE THREAD

**Issue by lifenautjoe** [yadaniyil/flutter_badges#2]
Following in the awesome practice from flutter of allowing arbitrary widgets as icons, would be great to be able to use a widget as an icon.

For example and Image, a custom icon or anything really.

**Comment by ebot64** [comment]
Yes @lifenautjoe anything really, even a text. The badge [here](https://pub.dartlang.org/packages/badge) would have served my purpose but its incompatible with dart 2

**Comment by yadaniyil** [comment]
Done! Check it out.
