### ISSUE TITLE
Splash color

### ISSUE THREAD

**Issue by felipecesar42** [yadaniyil/flutter_badges#5]
It would be nice to expose more elements from the final Icon button that will be generated like the splash color

**Comment by yadaniyil** [comment]
Hello @felipecesar42. Could you please clarify what do you mean?

**Comment by felipecesar42** [comment]
Sorry, when I wrote issue I was looking to another source code and misunderstood who the Badge package is made. I thought it was building the Badge Button using the `IconButton`  from the material package and the Icon Button has some attributes that I would like to have in the Badge like the splash color when tapping the badge. Not sure if it's viable now. I guess you can close this issue if the widgets used for this package doesn't have more interesting attributes do expose in the constructor of the Badge

**Comment by yadaniyil** [comment]
You can use IconButton as a Badge child and use every attribute of it.

```dart
	Badge(
      position: BadgePosition.topRight(top: 0, right: 3),
      badgeContent: Text('!'),
      child: IconButton(icon: Icon(Icons.shopping_cart), splashColor: Colors.blue),
    );
```

**Comment by felipecesar42** [comment]
Nice! Thanks for the help :D
