### ISSUE TITLE
All badges in a row are animated if only one of then should be updated

### ISSUE THREAD

**Issue by udiedrichsen** [yadaniyil/flutter_badges#6]
Hi,

Good package, thx for that!

I have an issues with that (from your example):

          actions: <Widget>[
            _shoppingCartBadge(_counter),
            _shoppingCartBadge(_counter2),
          ],

If _counter is increased both badge are animated. My expectation is that only the first badge gets an animation. Any way to avoid that?

**Comment by yadaniyil** [comment]
Hi @udiedrichsen. Thanks a lot.
Try a new version of the package (1.0.3). The bug should be fixed there.
The fix should work only for Text or Icon passed into badgeContent.
If you have better fix feel free to suggest or create PR.

**Comment by udiedrichsen** [comment]
Thx, it's fixed!
