### ISSUE TITLE
animationDuration not working

### ISSUE THREAD

**Issue by MahdiPishguy** [yadaniyil/flutter_badges#7]
this codes not work 

`animationDuration: Duration(milliseconds: 100),`
or
`animationDuration: Duration(seconds: 1000),`

**Comment by yadaniyil** [comment]
Hello @MahdiPishguy.
Seems like you use hot reload in order to update the duration.
To update animation Flutter needs a hot restart (green run button in Android Studio).
For more info: https://github.com/flutter/flutter/issues/24291.
Please respond if it helped you.
